### ISSUE TITLE
404 error with lists file

### ISSUE THREAD

**Issue by acosonic** [MrJeffLarry/redmine-cli#39]
both urls give 404 ...

curl -s --compressed "https://mrjefflarry.github.io/redmine-cli/apt/public_key.gpg" | sudo apt-key add -
sudo curl -s --compressed -o /etc/apt/sources.list.d/redmine-cli.list "https://mrjefflarry.github.io/redmine-cli/apt/redmine-cli.list"
sudo apt update
sudo apt install red-cli

**Comment by MrJeffLarry** [comment]
Hi!

Thanks for reporting, i see the problem, ill fix it ASAP
